# use the latest ubuntu environment (18.04) available on travis
dist: xenial

language: go

# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.13 lands.
env:
  - GO111MODULE=on GOOS_=linux GOARCH_=amd64

go:
  - "1.14.3"
  - "1.13"

# Only clone the most recent commit.
git:
  depth: 1

before_install:
  # install e2e test dependencies
  - sudo apt-get -y install socket

# Skip the install step.
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

#before_script:
#  -

# TODO lint
script:
  - GOOS=${GOOS_} GOARCH=${GOARCH_} make build;
  - make e2e-test # only run tests on pull requests
